AMQP_URI: amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_HOST}:${RABBIT_PORT}/
REDIS_URIS:
 development: redis://${REDIS_HOST}:${REDIS_PORT}/1

MONGODB_CONNECTION_URL: mongodb://127.0.0.1:27017
MONGODB_DB_NAME: db

MONGODB_USER: admin
MONGODB_PASSWORD: pass